### ISSUE TITLE
Laravel 6.* support

### ISSUE THREAD

**Issue by affektde** [botman/tinker#14]
Hello team,
will this package have Laravel 6.* support? <3

**Comment by stefandanaita** [comment]
@mpociot can you please have a look at this PR? Annoyingly tinker doesn't work with Laravel 6...

**Comment by vesper8** [comment]
@mpociot can you please make this package as well as studio-addons compatible with Laravel 6 (and 7 too since it's very close to being released)

Thank you very much

**Comment by stefandanaita** [comment]
😭
