### ISSUE TITLE
Use redis cache on tinker

### ISSUE THREAD

**Issue by iboldurev** [botman/tinker#2]
hello when I try to use the Redis cache driver, I have a problem

Change BotManTinker Command file

`$botman = BotManFactory::create($config, new RedisCache());`

When I try to handle an exception triggered

`[Exception]
  Serialization of 'Closure' is not allowed`

**Comment by mpociot** [comment]
Tinker does not need to cache responses. That's why it only runs with the ArrayCache hardcoded.
